### ISSUE TITLE
[BUG] ENABLE_MAPBOX Environment ignored?

### ISSUE THREAD

**Issue by stumpylog** [alextran1502/immich#222]
**Describe the bug**
Although my .env file includes `ENABLE_MAPBOX=false`, it appears the microservices container is still attempting to connect to MapBox:

```
immich-microservices     | [Nest] 29  - 06/12/2022, 4:59:56 PM   ERROR [ExceptionHandler] Cannot create a client without an access token
immich-microservices     | Error: Cannot create a client without an access token
immich-microservices     |     at NodeClient.MapiClient (/usr/src/app/node_modules/@mapbox/mapbox-sdk/lib/classes/mapi-client.js:25:11)
immich-microservices     |     at new NodeClient (/usr/src/app/node_modules/@mapbox/mapbox-sdk/lib/node/node-client.js:7:14)
immich-microservices     |     at createNodeClient (/usr/src/app/node_modules/@mapbox/mapbox-sdk/lib/node/node-client.js:24:10)
immich-microservices     |     at /usr/src/app/node_modules/@mapbox/mapbox-sdk/services/service-helpers/create-service-factory.js:13:16
immich-microservices     |     at new MetadataExtractionProcessor (/usr/src/app/apps/microservices/src/processors/metadata-extraction.processor.ts:30:45)
immich-microservices     |     at Injector.instantiateClass (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:301:19)
immich-microservices     |     at callback (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:48:41)
immich-microservices     |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
immich-microservices     |     at Injector.resolveConstructorParams (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:124:24)
immich-microservices     |     at Injector.loadInstance (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:52:9)
```

**Task List**
- [x] I have read thoroughly the README setup and installation instructions.
- [x] If my setup is different, I have included my docker-compose file.
- [x] I have included my redacted `.env` file. (no changes beyond UPLOAD_LOCATION) 
- [x] I have included information on my machine, and environment.

**To Reproduce**
Create the docker-compose.yml based on existing example.

**Expected behavior**
The container shouldn't try to connect to mapbox

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04, amd64

**Additional context**

**Comment by alextran1502** [comment]
I found the bug, will push out the fix soon

Thank you
