### ISSUE TITLE
[BUG] Web viewer wrongly sorts images uploaded from the web

### ISSUE THREAD

**Issue by SirBogner** [alextran1502/immich#281]
**Describe the bug**
When uploading images using the web viewer, some images show the right date in the EXIF-metadata-panel, but gets sorted to the wrong date in the timeline. 

**Task List**
- [x] I have read thoroughly the README setup and installation instructions.
- [ ] If my setup is different, I have included my docker-compose file.
- [ ] I have included my redacted `.env` file.
- [ ] I have included information on my machine, and environment.

**To Reproduce**
1. Go to immich from a web browser
2. Click on 'Upload'
3. Upload my dummy image
4. See error in the sorting

**Expected behavior**
Images to be sorted correctly date-wise.

**Dummy-file**
![dummy](https://user-images.githubusercontent.com/83633524/176557053-4dcdfcfd-ca00-447c-b8ef-f4843d9ed5e5.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by alextran1502** [comment]
Is this issue still relevant after our conversation on Discord? The image is sorted by the creation date in the EXIF info if it is found, otherwise the creation date will be the time it gets added to the database

**Comment by SirBogner** [comment]
Yes, it is still relevant. The issue is only present for the web viewer as shown in the pictures (marked as red). The mobile app (Android) functions just fine.

![Info0](https://user-images.githubusercontent.com/83633524/176991526-1e31222b-7dd2-435c-a607-34444a30d881.png) ![Info1](https://user-images.githubusercontent.com/83633524/176991524-e58f411c-ce7b-47cc-a802-5d494fe42c06.png)

**Comment by SirBogner** [comment]
And another question: When no creation date is present in the EXIF dataset, does Immich create the EXIF variable in the image metadata? This could be useful for those who would like to later extract the images and use them and the EXIF creation date elsewhere.

**Comment by alextran1502** [comment]
> And another question: When no creation date is present in the EXIF dataset, does Immich create the EXIF variable in the image metadata? This could be useful for those who would like to later extract the images and use them and the EXIF creation date elsewhere. 

At the moment, there is not. There is a feature put in for editing exif metadata though.

**Comment by alextran1502** [comment]
> Yes, it is still relevant. The issue is only present for the web viewer as shown in the pictures (marked as red). The mobile app (Android) functions just fine.
> 
> 
> 
> ![Info0](https://user-images.githubusercontent.com/83633524/176991526-1e31222b-7dd2-435c-a607-34444a30d881.png) ![Info1](https://user-images.githubusercontent.com/83633524/176991524-e58f411c-ce7b-47cc-a802-5d494fe42c06.png)
> 
> 
> 

I think I saw the problem. The date is the same but the year is different. I think I didn't consider the year when grouping the photos

**Comment by SirBogner** [comment]
> > I think I saw the problem. The date is the same but the year is different. I think I didn't consider the year when grouping the photos

I am happy to be able to help the hard working people!

**Comment by alextran1502** [comment]
Hey @SirBogner, I tried to recreate the scenario with the same date, and month but with different years, and on my system, it recognizes the difference to group them differently. 

Can you help me find a set of photoes that are correctly and incorrectly grouped together and that are not too sensitive and send it to me to test? You can send it on Discord DM.

Thank you for your support

**Comment by SirBogner** [comment]
Sure I can!

I will send you a DM
