### ISSUE TITLE
[BUG] Web viewer shows dublicated image extensions

### ISSUE THREAD

**Issue by SirBogner** [alextran1502/immich#282]
**Describe the bug**
When uploading images using the web viewer, some images show dublicated image extensions. For example the attatched image "dummy.jpg.jpg"

**Task List**
- [x] I have read thoroughly the README setup and installation instructions.
- [ ] If my setup is different, I have included my docker-compose file.
- [ ] I have included my redacted `.env` file.
- [ ] I have included information on my machine, and environment.

**To Reproduce**
1. Go to immich from a web browser
2. Click on 'Upload'
3. Upload my dummy image
4. See error in the sorting

**Expected behavior**
Images to only show the extension once.

**Dummy-file**
![dummy](https://user-images.githubusercontent.com/83633524/176557053-4dcdfcfd-ca00-447c-b8ef-f4843d9ed5e5.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 11
