### ISSUE TITLE
[BUG] HEVC / H.265 .mp4 videos are not playable on web interface

### ISSUE THREAD

**Issue by EnderPicture** [alextran1502/immich#307]
**Describe the bug**
HEVC / H.265 videos ending in .mp4 can not play on the web player.
Currently it shows a black screen with only the audio portion playing

**Task List**
- [x] I have read thoroughly the README setup and installation instructions.
- [x] If my setup is different, I have included my docker-compose file.
- [ ] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**To Reproduce**
1. Backup attached video captured on a galaxy s22 4k 30fps hevc
[bbecf97e-2c88-41ac-9872-73ed0fe66a43.zip](https://github.com/alextran1502/immich/files/9043882/bbecf97e-2c88-41ac-9872-73ed0fe66a43.zip)

2. Click on video in web interface
3. See black screen with audio playing

**Expected behavior**
Video should be playing on web interface.

**Screenshots**
![Screenshot from 2022-07-04 23-42-09](https://user-images.githubusercontent.com/16552062/177265865-4d82aea8-a821-456b-b386-29f6210bdf71.png)
![Screenshot from 2022-07-04 23-42-31](https://user-images.githubusercontent.com/16552062/177265870-cd7804ba-dec0-4ac3-9bdd-b6a319895cc7.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox

**Additional context**

**Comment by zackpollard** [comment]
Hey, currently the video encoding only functions for MOV files. We have work planned to extend this to all files on the server which will hopefully be completed soon. You can track the status of these changes by following #203. Closing as duplicate.
