### ISSUE TITLE
Album feature on the web

### ISSUE THREAD

**Issue by alextran1502** [alextran1502/immich#342]
# Album
Add album features to the web, including both shared and non-shared albums.

# Tasks
- [X] Add album page and view assets in album #352 
- [X] Add shared page and view assets in shared album #355 
- [x] Add view asset detail of album #358 
- [X] Add create album feature #365 
- [X] Add/remove shared users of an existing album #369 
- [X] Add/remove additional assets to an existing album #371 
- [X] Delete album #373 
- [X] Show message on empty album/sharing page - merge directly to main
- [X] Directly upload assets to the album #379 
- [X] Mechanism to choose the album cover #383

**Comment by Eidenz** [comment]
Does "Add/remove additional assets to an existing album" includes being able to upload new pictures directly to an album (rather than first uploading, then modifying album to add them)?

**Comment by alextran1502** [comment]
@Eidenz I saw that feature on Google Photos as well. I will add a step to this PR

**Comment by alextran1502** [comment]
Completed
